-- 상반기 아이스크림 총주문량이 3,000보다 높으면서 아이스크림의 주 성분이 과일인 아이스크림의 맛을 총주문량이 큰 순서대로 조회하는 SQL 문을 작성해주세요.
SELECT COMBINED_TABLE.FLAVOR
FROM (
    SELECT FIRST_HALF.SHIPMENT_ID
         , FIRST_HALF.FLAVOR
         , FIRST_HALF.TOTAL_ORDER
         , ICECREAM_INFO.INGREDIENT_TYPE
    FROM FIRST_HALF 
    INNER JOIN ICECREAM_INFO
    ON FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
) AS COMBINED_TABLE
WHERE COMBINED_TABLE.TOTAL_ORDER > 3000
AND COMBINED_TABLE.INGREDIENT_TYPE = 'fruit_based'
ORDER BY COMBINED_TABLE.TOTAL_ORDER DESC;